<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Models\**" />
    <EmbeddedResource Remove="Models\**" />
    <None Remove="Models\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Forge\MavethDigital.Forge.Core\MavethDigital.Forge.Core.csproj" />
    <ProjectReference Include="..\..\..\Forge\MavethDigital.Forge.Domain\MavethDigital.Forge.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
